federation_version: 2
subgraphs:
  hosts:
    routing_url: http://localhost:4001/
    schema:
      subgraph_url: http://localhost:4001/
  listings:
    routing_url: http://localhost:4002/
    schema:
      subgraph_url: http://localhost:4002/
  bookings:
    routing_url: http://localhost:4003/
    schema:
      subgraph_url: http://localhost:4003/