federation_version: 2
subgraphs:
  hosts:
    routing_url: https://xprqnj9t88.execute-api.us-east-1.amazonaws.com/
    schema:
      file: ../small-island-travel-guide-api-hosts/src/schema.graphql
  listings:
    routing_url: https://v2rzc9q824.execute-api.us-east-1.amazonaws.com/
    schema:
      file: ../small-island-travel-guide-api-listings/src/schema.graphql
  bookings:
    routing_url: https://xnzegn1gvg.execute-api.us-east-1.amazonaws.com/
    schema:
      file: ../small-island-travel-guide-api-bookings/src/schema.graphql